Repository canonical/sphinx-docs-starter-pack, pull requests merged in 2025-03, with the labels that each got.

#347 Remove Makefile.sp target
  docs/Makefile
Labels: enhancement

#353 Allow users optionally define which host IP address to bind
  docs/Makefile
Labels: question

#360 Add sphinx-docs-guide files and establish organization
  docs/.custom_wordlist.txt
  docs/conf.py
  docs/how-to/build.rst
  docs/how-to/contributing-myst.md
  docs/how-to/contributing.rst
  docs/how-to/customise.rst
  docs/how-to/edit.rst
  docs/how-to/guidance.rst
  docs/how-to/index.rst
  docs/how-to/migrate-from-pre-extension.rst
  docs/how-to/prereqs.rst
  docs/how-to/rtd.rst
  docs/how-to/update.rst
  docs/index.rst
  docs/reference/automatic_checks.rst
  docs/reference/automatic_checks_accessibility.rst
  docs/reference/automatic_checks_inclusivelanguage.rst
  docs/reference/automatic_checks_links.rst
  docs/reference/automatic_checks_spelling.rst
  docs/reference/automatic_checks_styleguide.rst
  docs/reference/doc-cheat-sheet-myst.md
  docs/reference/doc-cheat-sheet.rst
  docs/reference/include.txt
  docs/reference/index.rst
  docs/reference/style-guide-myst.md
  docs/reference/style-guide.rst
  docs/reuse/links.txt
  docs/reuse/substitutions.txt
  docs/reuse/substitutions.yaml
  docs/tutorial/index.rst
  docs/tutorial/mock-tutorial-example.png
  docs/tutorial/set-up-automated-testing.rst
  docs/tutorial/set-up.rst
Labels: documentation

#368 Update links and references to style guides
  docs/how-to/contributing.rst
  docs/how-to/guidance.rst
  docs/reference/automatic_checks_spelling.rst
  docs/reference/doc-cheat-sheet-myst.md
  docs/reference/doc-cheat-sheet.rst
  docs/reference/style-guide-myst.md
  docs/reference/style-guide.rst
  docs/reuse/links.txt
Labels: documentation
